providers = ["node", "python"]

[variables]
NODE_ENV = 'production'

[deploy]
startCommand = "cd uxersii && npm install"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10