providers = ["node", "python"]

[variables]
NODE_ENV = 'production'

[deploy]
startCommand = "cd uxersii && npm install && npm run build && cd .. && python manage.py migrate && python manage.py collectstatic && gunicorn uxersiiDjango.wsgi"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10