providers = ["node", "python"]

[variables]
NODE_ENV = 'production'

[deploy]
buildCommand: "npm run build"
startCommand: "cd uxersii && npm install && npm run start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10