providers = ["node"]

[variables]
NODE_ENV = 'production'

[deploy]
startCommand = "cd uxersii && npm install && npm start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10