# Generated by Django 5.0 on 2024-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uxerSiitoBack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('correo_admin', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=50, null=True)),
                ('contra_admin', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=20, null=True)),
                ('nombre_admin', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=30, null=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdministradorEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'administrador_est',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdministradorHog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'administrador_hog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdministradorOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'administrador_org',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id_alim', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_alim', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('fecha_cad', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alimentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompraHog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'compra_hog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompraOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'compra_org',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id_dona', models.AutoField(primary_key=True, serialize=False)),
                ('catn_adon', models.IntegerField(blank=True, null=True)),
                ('nomb_alim_dona', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('fecha_cad_dona', models.DateField(blank=True, db_column='fecha_Cad_dona', null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstableAlim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'estable_alim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstableDona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'estable_dona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstableEve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'estable_eve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_eve', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_eve', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=50, null=True)),
                ('fecha_eve', models.DateField(blank=True, null=True)),
                ('desc_eve', models.TextField(blank=True, null=True)),
                ('cp_eve', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=6, null=True)),
                ('tipo_eve', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=30, null=True)),
                ('num_asist', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HogarAlim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hogar_alim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HogarDona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hogar_dona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HogarEve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hogar_eve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insignias',
            fields=[
                ('id_ins', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_ins', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
            ],
            options={
                'db_table': 'insignias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id_mens', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('hora_men', models.DateTimeField(blank=True, null=True)),
                ('usuario_envia', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=50, null=True)),
                ('tipo_usuario', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=20, null=True)),
            ],
            options={
                'db_table': 'mensajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObtieneEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'obtiene_est',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObtieneHog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'obtiene_hog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgAlim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'org_alim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgDona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'org_dona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgEve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'org_eve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntosColecta',
            fields=[
                ('id_punto', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_punto', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('responsable', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=255, null=True)),
                ('almacenamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('fecha_de_creacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'puntos_colecta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioEstablecimiento',
            fields=[
                ('id_est', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_est', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=50, null=True)),
                ('cp_est', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=6, null=True)),
                ('contra_est', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=25, null=True)),
                ('correo_est', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=50, null=True)),
                ('tel_est', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=20, null=True)),
                ('desc_est', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('tipo_redest', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=12, null=True)),
                ('link_redest', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=250, null=True)),
                ('fotoest', models.TextField(blank=True, db_column='fotoEst', null=True)),
            ],
            options={
                'db_table': 'usuario_establecimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioHogar',
            fields=[
                ('id_hog', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hog', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=20, null=True)),
                ('apellido_mat', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=20, null=True)),
                ('apellido_pat', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=20, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('correo_hog', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=50, null=True)),
                ('contra_hog', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=25, null=True)),
                ('desc_hog', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('genero', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=20, null=True)),
                ('nombuserh', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='nombUserH', max_length=15, null=True)),
                ('codigopostal', models.IntegerField(blank=True, db_column='codigoPostal', null=True)),
                ('fotoh', models.TextField(blank=True, db_column='fotoH', null=True)),
            ],
            options={
                'db_table': 'usuario_hogar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioOrganizacion',
            fields=[
                ('id_ofc', models.CharField(db_collation='utf8mb3_general_ci', max_length=15, primary_key=True, serialize=False)),
                ('nombre_org', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=50, null=True)),
                ('cp_org', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=6, null=True)),
                ('contra_org', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=20, null=True)),
                ('correo_org', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=50, null=True)),
                ('desc_org', models.TextField(blank=True, null=True)),
                ('tel_org', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=20, null=True)),
                ('tipo_redorg', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=12, null=True)),
                ('link_org', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=250, null=True)),
                ('fotoorg', models.TextField(blank=True, db_column='fotoOrg', null=True)),
            ],
            options={
                'db_table': 'usuario_organizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'venta_est',
                'managed': False,
            },
        ),
    ]
