# Generated by Django 5.0 on 2024-03-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uxerSiitoBack', '0002_administrador_administradorest_administradorhog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstableDona',
        ),
        migrations.DeleteModel(
            name='HogarDona',
        ),
        migrations.DeleteModel(
            name='OrgDona',
        ),
        migrations.AlterModelOptions(
            name='usuariohogar',
            options={'managed': True},
        ),
    ]
