# Generated by Django 5.0 on 2024-04-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uxerSiitoBack', '0004_rename_nombuserh_usuariohogar_nombuserh_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdministradorEst',
        ),
        migrations.DeleteModel(
            name='AdministradorOrg',
        ),
        migrations.DeleteModel(
            name='CompraOrg',
        ),
        migrations.DeleteModel(
            name='EstableAlim',
        ),
        migrations.DeleteModel(
            name='EstableEve',
        ),
        migrations.DeleteModel(
            name='Eventos',
        ),
        migrations.DeleteModel(
            name='HogarEve',
        ),
        migrations.DeleteModel(
            name='Insignias',
        ),
        migrations.DeleteModel(
            name='ObtieneEst',
        ),
        migrations.DeleteModel(
            name='ObtieneHog',
        ),
        migrations.DeleteModel(
            name='OrgAlim',
        ),
        migrations.DeleteModel(
            name='OrgEve',
        ),
        migrations.DeleteModel(
            name='UsuarioEstablecimiento',
        ),
        migrations.DeleteModel(
            name='UsuarioOrganizacion',
        ),
        migrations.DeleteModel(
            name='VentaEst',
        ),
        migrations.AlterModelOptions(
            name='administrador',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='administradorhog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='alimentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comprahog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='donaciones',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hogaralim',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mensajes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='puntoscolecta',
            options={'managed': True},
        ),
    ]
