# Generated by Django 5.0 on 2024-04-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uxerSiitoBack', '0005_delete_administradorest_delete_administradororg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('id_hog', models.IntegerField(blank=True, null=True)),
                ('id_alim', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carrito',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='administradorhog',
            name='id_admin',
            field=models.ForeignKey(blank=True, db_column='id_admin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uxerSiitoBack.administrador'),
        ),
        migrations.AddField(
            model_name='administradorhog',
            name='id_hog',
            field=models.ForeignKey(blank=True, db_column='id_hog', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uxerSiitoBack.usuariohogar'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='id_punto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='imagen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comprahog',
            name='id_alim',
            field=models.ForeignKey(blank=True, db_column='id_alim', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uxerSiitoBack.alimentos'),
        ),
        migrations.AddField(
            model_name='comprahog',
            name='id_hog',
            field=models.ForeignKey(blank=True, db_column='id_hog', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uxerSiitoBack.usuariohogar'),
        ),
        migrations.AddField(
            model_name='donaciones',
            name='id_punto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donaciones',
            name='nombUserH',
            field=models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='nombUserH', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hogaralim',
            name='id_alim',
            field=models.ForeignKey(blank=True, db_column='id_alim', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uxerSiitoBack.alimentos'),
        ),
        migrations.AddField(
            model_name='hogaralim',
            name='id_hog',
            field=models.ForeignKey(blank=True, db_column='id_hog', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uxerSiitoBack.usuariohogar'),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='id_admin',
            field=models.ForeignKey(blank=True, db_column='id_admin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uxerSiitoBack.administrador'),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='id_hog',
            field=models.ForeignKey(blank=True, db_column='id_hog', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uxerSiitoBack.usuariohogar'),
        ),
        migrations.AddField(
            model_name='puntoscolecta',
            name='valcod',
            field=models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuariohogar',
            name='numDonaciones',
            field=models.IntegerField(blank=True, db_column='numDonaciones', null=True),
        ),
        migrations.AlterField(
            model_name='donaciones',
            name='estatus',
            field=models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='estatus', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donaciones',
            name='fecha_cad_dona',
            field=models.DateField(blank=True, db_column='fecha_cad_dona', null=True),
        ),
        migrations.AlterField(
            model_name='donaciones',
            name='id_dona',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
